spring:
  datasource:
    url: jdbc:mysql://rm-cn-lbj3ffe7l000sqno.rwlb.rds.aliyuncs.com:3306/project-xbt
    username: pg
    password: root@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: HikariPool
      max-lifetime: 1800000
      connection-timeout: 20000
      initialization-mode: always
  redis:
    host: 111.231.98.138
    port: 6379
    password:
    database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xbt.mybatis.model
server:
  port: 18080